### ISSUE TITLE
Change base image (Crash upon startup in v0.111)

### ISSUE THREAD

**Issue by Ad5001** [xDevBase/hugo-builder#1]
I've recently updated to the newest version of hugo-builder to version 0.111. However, said version seems to have added new library incompatibility, making hugo crash immediately upon launch:

```
root@server:~# docker run --rm -it xdevbase/hugo-builder hugo help
Error loading shared library libresolv.so.2: No such file or directory (needed by /usr/local/bin/hugo)
Error relocating /usr/local/bin/hugo: __res_search: symbol not found
```

This does not happen in prior versions, so rolling back is a solution for now. It seems to be a problem related to the image being based on Alpine, as several other docker images based on it seem to share the same issue (due to slight differences between `glibc` and `musl`). Would it be possible to switch to a base image that uses `glibc`?

**Comment by harrtho** [comment]
Hey @Ad5001,
thank you for pointing me to this error. I will take a look if I find a more elegant solution. Maybe I will build hugo from source with static linking. For the time being I pushed a significant bigger images based on ubuntu.

Do you have a specific base image in mind?

**Comment by harrtho** [comment]
The problem should be solved and the version on docker hub is updated.

**Comment by Ad5001** [comment]
Just tested, the problem is solved! Thanks!
